[package]
name = "chip8-rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "chip8"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19"