[package]
name = "chip8_core"
version = "0.1.0"
edition = "2021"

[features]
std = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }